spring:
    devtools:
        restart:
            enabled: false
        livereload:
            enabled: false
    datasource:
            driver-class-name: com.mysql.jdbc.Driver
            url: jdbc:mysql://${DB_HOSTNAME:localhost}:${DB_PORT:3306}/${DB_NAME:porrasdb}?useUnicode=true&characterEncoding=utf8&useSSL=false&sessionVariables=time_zone='Europe/Madrid'
            name:
            username: ${RDS_USERNAME:}
            password: ${RDS_PASSWORD:}
        jpa:
            database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
            database: MYSQL
            show_sql: false
            properties:
                hibernate:
                    generate_statistics: false
    jpa:
        database: HSQL
        show_sql: true
        properties:
            hibernate:
                format-sql: false
                generate-statistics: true
server:
    port: 8080