spring:
    profiles:
            active: dev
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: true
    jpa:
        database: HSQL
        show-sql: true
        properties:
            hibernate.dialect: org.hibernate.dialect.HSQLDialect
        hibernate:
            naming.strategy: org.hibernate.cfg.ImprovedNamingStrategy
            ddl-auto: none
    datasource:
        driver-class-name: org.h2.Driver
        platform: h2
        url: jdbc:h2:mem:porrasdb;create=true
        username: sa
        password:
        initialize: true
    h2:
        console:
            enabled: true
server:
    port: 8080